filters:
  price_min: 50000
  price_max: 90000
  beds_min: 1
  beds_max: 3
  areas:
  - battaramulla
  - rajagiriya
  - dehiwala
  - mount lavinia
  - boralesgamuwa
  - bambalapitiya

sources:
  - https://ikman.lk/en/ads/colombo/house-rentals?money.price.minimum=50000&money.price.maximum=90000
  - https://ikman.lk/en/ads/colombo/apartment-rentals?money.price.minimum=50000&money.price.maximum=90000

gmail:
  enabled: false

telegram:
  enabled: true

whatsapp:
  enabled: false
